head(airquality)
airquality$Date=as.Date(paste(1973,airquality$Month,airquality$Day,sep="-"))
plot(Ozone~Date,airquality,col="red")
model3=gls(Ozone~Wind,data=airquality,na.action = na.exclude)
air2=subset(airquality,complete.cases(Ozone))
model4=gls(Ozone~Wind*Date,air2)
plot(ACF(model4,form=~Date),alpha=0.05)
model5=update(model5,correlation=corAR1())
library(MuMin)
AICc(model4,model5)
