plot(Ozone~Wind,data=airquality)
model1=lm(Ozone~Wind,data=airquality)
coefficients(model1)
plot(model1)
model2=glm(Ozone~Wind,data=airquality,family = poisson)
coefficients(model2)
plot(model2)
airquality=na.omit(airquality)
model3=gls(Ozone~Wind,data = airquality)
coefficients(model3)
model4=gls(Ozone~Wind*Date,data=airquality)
plot(ACF(model4),alpha=0.05)
model5=update(model4,correlation=corAR1())
library(MuMIn)
AICc(model5,model4)
